#!/bin/sh
if [ "$WAIT_DB" != yes ]; then
    log WARNING Not waiting for a postgres server
    exit 0
fi

log INFO Waiting until postgres is listening at $PGHOST...
while true; do
    psql --list > /dev/null 2>&1 && break
    sleep 1
done
