#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os

import odoobaselib

logging.info(
    "Linking all addons from %s in %s",
    odoobaselib.ADDONS_YAML,
    odoobaselib.ADDONS_DIR)

for repo, addons in odoobaselib.addons_config().items():
    while addons:
        addon = addons.pop()
        if addon == '*':
            addon_dir = os.path.join(odoobaselib.SRC_DIR, repo)
            try:
                modules = next(os.walk(addon_dir))[1]
            except StopIteration:
                continue
            for module in modules:
                if not module.startswith('.') and module != 'setup':
                    addons.append(module)
            continue
        src = os.path.relpath(
            os.path.join(odoobaselib.SRC_DIR, repo, addon),
            odoobaselib.ADDONS_DIR)
        dst = os.path.join(odoobaselib.ADDONS_DIR, addon)
        try:
            ok = os.readlink(dst) == src
        except OSError:
            ok = False
        if not ok:
            try:
                os.remove(dst)
            except OSError:
                pass
            os.symlink(src, dst)
            logging.debug("Linked %s in %s", src, dst)
