#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os
import sys

import odoobaselib

if not odoobaselib.LINK:
    logging.warning("Not linking addons")
    sys.exit()

logging.info(
    "Linking all addons from %s in %s",
    odoobaselib.ADDONS_YAML,
    odoobaselib.ADDONS_DIR)

for repo, addons in odoobaselib.addons_config().items():
    while addons:
        addon = addons.pop()
        if addon == '*':
            addon_dir = os.path.join(odoobaselib.SRC_DIR, repo)
            try:
                modules = next(os.walk(addon_dir))[1]
            except StopIteration:
                continue
            for module in modules:
                if not module.startswith('.') and module != 'setup':
                    addons.append(module)
            continue
        src = os.path.join(odoobaselib.SRC_DIR, repo, addon)
        dst = os.path.join(odoobaselib.ADDONS_DIR, addon)
        if not os.path.exists(dst):
            logging.debug("Linking %s in %s", src, dst)
            os.symlink(src, dst)
