#!/usr/bin/env bash
if [[ "$GEOIP_ACCOUNT_ID" != "" && "$GEOIP_LICENSE_KEY" != "" ]] ; then
    set -e
    # see https://dev.maxmind.com/geoip/geoipupdate/
    log INFO "Activating GeoIP/GeoLite2 updates"
    log INFO "This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com"
    sed 's/^AccountID\s.*$/AccountID '"$GEOIP_ACCOUNT_ID"'/g;s/^LicenseKey\s.*$/LicenseKey '"$GEOIP_LICENSE_KEY"'/g' /etc/GeoIP.conf > /tmp/GeoIP.conf
    cat /tmp/GeoIP.conf > /etc/GeoIP.conf
    rm /tmp/GeoIP.conf
fi

if [[ "$(grep 'AccountID' /etc/GeoIP.conf | sed 's/AccountID //')" != "0" ]] ; then
    set -e
    geoipupdate
fi
