#!/bin/bash

if [ -z "${WAIT_NOHOST}" ]; then
    exit 0
fi

log INFO "Waiting for the Odoo in ${WAIT_NOHOST} to stop"

while ping -c1 "${WAIT_NOHOST}" &> /dev/null; do
    log DEBUG "${WAIT_NOHOST} responded to ping"
    sleep 1
done

log INFO "${WAIT_NOHOST} has stopped responding"

exit 0
