version: "2.1"

services:
    odoo10:
        extends:
            file: common.yaml
            service: odoo
        build:
            args:
                # To aggregate in development, use `setup-devel.yaml`
                AGGREGATE: "no"
                # No need for this in development
                CLEAN: "no"
                COMPILE: "no"
        ports:
            # XXX I recommend you to use static ports per project
            - "8069"
            - "8072"
        volumes:
            - filestore10:/home/odoo/.local/share/Odoo
            - ./odoo/custom:/opt/odoo/custom:ro,z
        environment:
            PGDATABASE: devel
            # Don't optimize in development
            PYTHONOPTIMIZE: 0
            # XXX Use same static port as in `wdb` service below
            WDB_WEB_PORT: "1984"
        links:
            - db10:db
            - smtp
            - wdb
        # Uncomment to start in unit test mode, add module names if you wish
        # command: unittest module1,module2
        command: odoo --dev all

    db10:
        extends:
            file: common.yaml
            service: db
        volumes:
            - db10:/var/lib/postgresql/data

    smtp:
        extends:
            file: common.yaml
            service: smtpfake

    wdb:
        image: yajo/wdb-server
        ports:
            # XXX I recommend you to use static ports per project
            - "1984"

volumes:
    filestore10:
    db10:
