version: "2.1"
services:
    odoo10:
        extends:
            file: common.yaml
            service: odoo
        bulid:
            args:
                # XXX These are critical for security
                ADMIN_PASSWORD: example secure password
                PROXY_MODE: "yes"
        restart: unless-stopped
        links:
            - db10:db
            - inbox
            - smtp
        networks:
            - back

    db10:
        extends:
            file: common.yaml
            service: db
        restart: unless-stopped
        networks:
            - back

    https:
        extends:
            file: common.yaml
            service: https
        links:
            - odoo10:www
        restart: unless-stopped
        links:
            - odoo10:www
        environment:
            STAGING: "false"
        networks:
            - back
            - front

    inbox:
        extends:
            file: common.yaml
            service: inboxreal
        restart: unless-stopped
        networks:
            - back

    smtp:
        extends:
            file: common.yaml
            service: smtpreal
        restart: unless-stopped
        networks:
            - back

    backup:
        extends:
            file: common.yaml
            service: backup
        restart: unless-stopped
        links:
            - db10:postgresdb
            - smtp
        volumes_from:
            - odoo10
        networks:
            - back

volumes:
    filestore10:
    db10:
    smtp:
    certs:
    certscron:

networks:
    back:
    front:
