version: "2.1"
services:
    odoo:
        extends:
            file: common.yaml
            service: odoo
        environment:
            PGDATABASE: test
            # You may want demo data for testing
            WITHOUT_DEMO: "false"
            SMTP_PORT: "1025"
        restart: unless-stopped
        depends_on:
            - cdnjs_cloudflare_proxy
            - db
            - fonts_googleapis_proxy
            - fonts_gstatic_proxy
            - smtp
        networks:
            default:
            inverseproxy_shared:
        labels:
            traefik.dbmanager.frontend.auth.basic:
                "${DB_USER}:${ODOO_ADMIN_PASSWORD_BCRYPT}"
            traefik.dbmanager.frontend.rule:
                "Host:${DOMAIN_TEST};PathPrefix:/web/database/"
            traefik.dbselector.frontend.rule:
                "Host:${DOMAIN_TEST};PathPrefix:/web/database/{p:selector|list}"
            traefik.longpolling.frontend.rule:
                "Host:${DOMAIN_TEST};PathPrefix:/longpolling/"
            traefik.websiteinfo.frontend.auth.basic:
                "${DB_USER}:${ODOO_ADMIN_PASSWORD_BCRYPT}"
            traefik.websiteinfo.frontend.rule:
                "Host:${DOMAIN_TEST};Path:/website/info"
            traefik.www.frontend.rule: "Host:${DOMAIN_TEST}"
        command:
            - odoo
            - --workers=2
            - --max-cron-threads=1

    db:
        extends:
            file: common.yaml
            service: db
        restart: unless-stopped

    smtp:
        extends:
            file: common.yaml
            service: smtpfake
        restart: unless-stopped
        networks:
            default:
            inverseproxy_shared:
        labels:
            traefik.docker.network: "inverseproxy_shared"
            traefik.enable: "true"
            traefik.frontend.passHostHeader: "true"
            traefik.port: "8025"
            traefik.frontend.rule: "Host:${DOMAIN_TEST};PathPrefixStrip:/smtpfake/"

    # Whitelist outgoing traffic for tests, reports, etc.
    cdnjs_cloudflare_proxy:
        image: tecnativa/whitelist
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - cdnjs.cloudflare.com
            public:
        environment:
            TARGET: cdnjs.cloudflare.com
            PRE_RESOLVE: 1

    fonts_googleapis_proxy:
        image: tecnativa/whitelist
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - fonts.googleapis.com
            public:
        environment:
            TARGET: fonts.googleapis.com
            PRE_RESOLVE: 1

    fonts_gstatic_proxy:
        image: tecnativa/whitelist
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - fonts.gstatic.com
            public:
        environment:
            TARGET: fonts.gstatic.com
            PRE_RESOLVE: 1

networks:
    default:
        internal: true
        driver_opts:
            encrypted: 1

    inverseproxy_shared:
        external: true

    public:

volumes:
    filestore:
    db:
