#!/usr/bin/env sh
# Copyright 2016 LasLabs Inc.
# License MIT or later (https://opensource.org/licenses/MIT).

set -e

sleep 7

curl --fail http://localhost:8069/web

echo "Curl passed on $DOCKER_CONTAINER_ID"
