HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html


<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="initial-scale=1">
        <title>My Project failed!</title>
        <link
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw=="
            crossorigin="anonymous">
        <style media="screen" type="text/css">
            .jumbotron{margin-top: 5em}
            .btn{white-space: normal}
        </style>
    </head>
    <body>
        <main class="container">
            <div class="jumbotron">
                <h1>
                    Welcome to My Project,
                    <small> but...</small>
                </h1>
                <p class="text-muted">
                    ... right now our site is under maintenance. This should
                    last for no more than 15 minutes, so try again soon please.
                </p>
                <p>
                    However, in the mean time, you can call us to
                    <a href="tel:+00000000000">+00 000 00 00 00</a>,
                    write us to
                    <a href="mailto:info@example.com">
                        info@example.com</a>
                    or come back later.
                </p>
                <p>
                    <a
                        class="btn btn-default"
                        href="tel:+00000000000">
                        I will call you
                    </a>
                    <a
                        class="btn btn-default"
                        href="mailto:info@example.com">
                        I will send you an email
                    </a>
                    <a
                        class="btn btn-primary"
                        href="https://www.facebook.com/example.com">
                        I will stalk you in Facebook in the mean time.
                    </a>
                </p>
            </div>
        </main>
    </body>
</html>
