#!/bin/bash
set -ex

# Get Odoo version
version="$DOCKER_TAG"
if [ "$version" == latest ]; then
    version=11.0
fi

if [ -z "$IMAGE_NAME" ]; then
    IMAGE_NAME="$DOCKER_REPO:$DOCKER_TAG"
fi

# See http://label-schema.org/rc1/#build-time-labels
for target in base onbuild; do
    suffix=''
    if [ "$target" == onbuild ]; then
        suffix="-$target"
    fi
    time docker image build \
        --build-arg VCS_REF="$GIT_SHA1" \
        --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
        --build-arg ODOO_VERSION="$version" \
        --file "$version.Dockerfile" \
        --tag "$IMAGE_NAME$suffix" \
        --target $target \
        .
done
