#!/bin/bash
set -ex

if [ "$DOCKER_TAG" == latest ]; then
    dockerfile=11.0.Dockerfile
else
    dockerfile="$DOCKER_TAG.Dockerfile"
fi

# See http://label-schema.org/rc1/#build-time-labels
time docker image build \
    --build-arg VCS_REF="$GIT_SHA1" \
    --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
    --build-arg ODOO_VERSION="$DOCKER_TAG" \
    --file "$dockerfile" \
    --tag "$IMAGE_NAME" \
    .
