#!/usr/bin/env python
import os
from glob import iglob

import docker

DEFAULT_VERSION = "11.0"
DOCKER_REPO = os.environ.get("DOCKER_REPO", "tecnativa/odoo-base")
DOCKER_TAG = os.environ.get("DOCKER_TAG")
IMAGE_NAME = os.environ.get("IMAGE_NAME", u"{}:{}")
CLIENT = docker.client.from_env()

if DOCKER_TAG == "latest":
    # Push other tags, that should have been built already
    for image in CLIENT.images.list(DOCKER_REPO):
        for tag in image.tags:
            if tag != IMAGE_NAME:
                CLIENT.images.push(tag)
