#!/bin/bash
set -ex
if [ "$DOCKER_TAG" == latest ]; then
    # Push other tags, that should have been built already
    source hooks/variables
    for ver in $DEFAULT_VERSION $VERSIONS; do
        docker push "$DOCKER_REPO:$ver"
    done
fi
