#!/bin/bash
set -ex

# Get Odoo version
version="$DOCKER_TAG"
if [ "$version" == latest ]; then
    version=11.0
fi

if [ -z "$IMAGE_NAME" ]; then
    IMAGE_NAME="$DOCKER_REPO:$DOCKER_TAG"
fi

docker image push "$IMAGE_NAME-onbuild"
