#!/bin/bash
set -ex
# Will help debugging https://github.com/docker/hub-feedback/issues/904
env
git --version
git remote -v
# Clone the scaffolding branch to use it as a test suite
GIT_REPO="$(git remote -v | grep fetch | awk '{ print $2}')"
git clone --branch scaffolding --single-branch --depth 1\
    "$GIT_REPO" scaffolding
