#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from plumbum import FG, local
from plumbum.cmd import docker  # noqa pylint: disable=import-error

REGISTRY = local.env["REGISTRY_USERNAME"]
REPO = local.env["DOCKER_REPO"]
VERSION = local.env["DOCKER_TAG"]

# Log all locally available images; will help to pin images
docker["image", "ls", "--digests", REPO] & FG

# Login in Docker Hub
docker(
    "login",
    "--username",
    REGISTRY,
    "--password",
    local.env["REGISTRY_TOKEN"],
    local.env["REGISTRY_HOST"],
)

# Push built images
for suffix in ("", "-onbuild"):
    # Prefix images with registry
    local_tag = f"{REPO}:{VERSION}{suffix}"
    public_tag = f"{REGISTRY}/{local_tag}"
    docker["image", "tag", local_tag, public_tag] & FG
    # Push to registry
    docker["image", "push", public_tag] & FG
    if VERSION == local.env.get("LATEST_RELEASE"):
        public_latest_tag = f"{REGISTRY}/{REPO}:latest{suffix}"
        docker["image", "tag", local_tag, public_latest_tag] & FG
        docker["image", "push", public_latest_tag] & FG
