#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function

import os
import shutil
import stat
import subprocess
import sys
from argparse import ArgumentParser
from tempfile import NamedTemporaryFile, mkstemp

from doodbalib import logger

# Define CLI options
parser = ArgumentParser(
    description="Execute some code in this container's QA environment."
)
parser.add_argument(
    "script",
    help="The source code that will be executed. It should start with a shebang.",
)
parser.add_argument(
    "arguments", nargs="*", help="Additional arguments passed to the script."
)
args = parser.parse_args()

# Copy the source code to an executable file
executable = NamedTemporaryFile(mode="w+", delete=False)
with executable as tmp:
    logger.debug("Insider script source code:\n%s", args.script)
    tmp.write(args.script)
os.chmod(
    executable.name,
    stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH,
)

# Execute the script
cmd = [executable.name] + args.arguments
returncode = 0
try:
    logger.debug("Executing %r", cmd)
    subprocess.check_call(
        cmd,
        stdout=sys.stderr,
        # TODO Change to text=True when we support Python 3.7+ only
        universal_newlines=True,
    )
except subprocess.CalledProcessError as error:
    logger.debug("Subcommand exception:", exc_info=True)
    returncode = error.returncode
finally:
    logger.debug("Deleting %s", executable.name)
    os.unlink(executable.name)

    artifacts_zip_path = mkstemp()[1]
    logger.debug("Zipping /qa/artifacts in %s.zip", artifacts_zip_path)
    shutil.make_archive(artifacts_zip_path, "zip", "/qa/artifacts")
    artifacts_zip_path += ".zip"
    with open(artifacts_zip_path, "rb") as zip_fd:
        if sys.version_info >= (3,):
            with os.fdopen(sys.stdout.fileno(), "wb", closefd=False) as stdout:
                stdout.write(zip_fd.read())
                stdout.flush()
        # TODO Delete when dropping Python 2 (Odoo 10.0 and lower) support,
        # as this is a less safe and idiomatic way of doing the same as above
        else:
            os.write(sys.stdout.fileno(), zip_fd.read())

    logger.debug("Deleting %s", artifacts_zip_path)
    os.unlink(artifacts_zip_path)

sys.exit(returncode)
