#!/bin/bash
ODOO_MOUNTPOINT="${ODOO_MOUNTPOINT:/mnt/odoo}"

set -e
if [ ! -d "/var/lib/odoo/filestore/${PGDATABASE}" ]
then
    log INFO Creating /var/lib/odoo/filestore/${PGDATABASE}
    if [ -d "/var/lib/odoo/filestore/${PGDATABASE}" ]
    then
        log INFO Backing up ${PGDATABASE} to ${PGDATABASE}$(date +%Y%m%d%H%M)
        cp -a /var/lib/odoo/filestore/${PGDATABASE} /var/lib/odoo/filestore/${PGDATABASE}$(date +%Y%m%d%H%M)
        psql -e "CREATE DATABASE ${PGDATABASE}$(date +%Y%m%d%H%M) WITH TEMPLATE ${PGDATABASE} OWNER ${PGUSER}"
    fi    
    if [ -d "/var/lib/odoo/filestore/${OPENUPGRADE_BASE_DB}" ]
    then
        cp -a /var/lib/odoo/filestore/${OPENUPGRADE_BASE_DB} /var/lib/odoo/filestore/${PGDATABASE}
        psql -e "CREATE DATABASE ${PGDATABASE} WITH TEMPLATE ${OPENUPGRADE_BASE_DB} OWNER ${PGUSER}"
        exit 0
    fi
    if [ -d "${ODOO_MOUNTPOINT}/filestore/${OPENUPGRADE_BASE_DB}" ]
        cp -a ${ODOO_MOUNTPOINT}/filestore/${OPENUPGRADE_BASE_DB} /var/lib/odoo/filestore/${PGDATABASE}
        psql -e "CREATE DATABASE ${PGDATABASE} WITH TEMPLATE ${OPENUPGRADE_BASE_DB} OWNER ${PGUSER}"
        exit 0
    fi
    exit 1
fi
