#!/usr/bin/env python
# Copyright 2017 LasLabs Inc.

import logging
import os

from odoobaselib import CUSTOM_DIR, FILE_APT_BUILD, SRC_DIR
from odoobaselib.installer import Installer, INSTALLERS


if os.path.isfile(FILE_APT_BUILD):
    Installer('apt', FILE_APT_BUILD).install()


for name in INSTALLERS:
    req_file = os.path.join(
        CUSTOM_DIR, 'dependencies', '%s.txt' % name,
    )
    if os.path.isfile(req_file):
        Installer(name, req_file).install()


# Deprecated
req_file = os.path.join(
    SRC_DIR, 'requirements.txt',
)
if os.path.isfile(req_file):
    new_file = os.path.join(
        CUSTOM_DIR, 'dependencies', 'pip.txt',
    )
    logging.warning(
        'The "%s" path is deprecated. Please use "%s" instead.',
        req_file, new_file,
    )
    Installer('pip', req_file).install()
