#!/usr/bin/env python
# Copyright 2017 LasLabs Inc.

import os

import odoobaselib
from installer import Installer


DIR_CUSTOM = odoobaselib.CUSTOM_DIR
FILE_APT_BUILD = os.path.join(
    DIR_CUSTOM, 'dependencies', 'apt_build.txt',
)
INSTALL = ['apt', 'gem', 'npm', 'pip']


if os.path.isfile(FILE_APT_BUILD):
    Installer('apt', FILE_APT_BUILD).install()


for name in INSTALL:
    req_file = os.path.join(
        DIR_CUSTOM, 'dependencies', '%s.txt' % name,
    )
    if os.path.isfile(req_file):
        Installer(name, req_file).install()


# Deprecated
req_file = os.path.join(
    DIR_CUSTOM, 'requirements.txt',
)
if os.path.isfile(req_file):
    new_file = os.path.join(
        DIR_CUSTOM, 'dependencies', 'pip.txt',
    )
    logging.warning(
        'The "%s" path is deprecated. Please use "%s" instead.',
        req_file, new_file,
    )
    Installer('pip', req_file).install()
