#!/usr/bin/env python

import logging
import os
import subprocess


SSH_DIR = '/opt/odoo/custom/ssh.d'
CONFIG_PATH = os.path.join(SSH_DIR, 'config')


if not os.path.isfile(CONFIG_PATH):
    logging.info('No SSH configuration found')
    exit(0)


HOMES = {
    'root': '/root',
    'odoo': '/opt/odoo',
}


def do_command(command_list):
    proc = subprocess.Popen(command_list)
    proc.communicate()


for user, directory in HOMES.items():
    logging.info('Setting up SSH for %s in %s', user, directory)
    user_ssh_dir = os.path.join(directory, '.ssh')
    do_command(['cp', '-R', SSH_DIR, user_ssh_dir])
    do_command(['chmod', '-R', 'u=rwX,go=', user_ssh_dir])
    do_command(['chown', '-R', user, user_ssh_dir])
