#!/usr/bin/env python
# Copyright 2017 LasLabs Inc.

from os.path import join
from glob import glob

from odoobaselib import (
    AUTO_REQUIREMENTS,
    CUSTOM_DIR,
    FILE_APT_BUILD,
    SRC_DIR,
)
from odoobaselib.installer import install, INSTALLERS


# Build dependencies installed before any others
install("apt", FILE_APT_BUILD)

for name in INSTALLERS:
    req_files = []
    # pip `requirements.txt` files found in repositories
    if name == "pip" and AUTO_REQUIREMENTS:
        req_files += glob(join(SRC_DIR, "*", "requirements.txt"))
    # Normal dependency installation
    req_files.append(join(CUSTOM_DIR, 'dependencies', '%s.txt' % name))
    for req_file in req_files:
        install(name, req_file)
