#!/bin/sh
set -e

# Check if the `addons.txt` file is provided
list=/opt/odoo/custom/src/addons.txt
if [ -f $list ]; then
    # Autocreate the addons directory
    dir=/opt/odoo/auto/addons
    log INFO Linking all addons from $list in $dir
    mkdir -p $dir
    cd $dir
    # Link each addon found in `addons.txt`
    while read -r line; do
        [[ "$line" =~ ^#.*$ ]] && continue
        if [ ! -z "$line" ]; then
            log DEBUG Linking $line
            ln -sf /opt/odoo/custom/src/$line .
        fi
    done < "$list"
else
    log WARNING Linking no addons: $list not found
fi
