#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os

import yaml

SRC_DIR = "/opt/odoo/custom/src"
ADDONS_YAML = SRC_DIR + "/addons.yaml"
ADDONS_DIR = "/opt/odoo/auto/addons"

logging.info("Linking all addons from %s in %s", ADDONS_YAML, ADDONS_DIR)

with open(ADDONS_YAML) as addons_file:
    config = yaml.load(addons_file)

for repo, addons in config.items():
    if addons == "all":
        addons = os.listdir(os.path.join(SRC_DIR, repo))
    for addon in addons:
        src = os.path.join(SRC_DIR, repo, addon)
        dst = os.path.join(ADDONS_DIR, addon)
        logging.debug("Linking %s in %s", src, dst)
        os.symlink(src, dst)
