#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os

import odoobaselib

logging.info(
    "Linking all addons from %s in %s",
    odoobaselib.ADDONS_YAML,
    odoobaselib.ADDONS_DIR)

for repo, addons in odoobaselib.addons_config().items():
    if addons == "all":
        addons = os.listdir(os.path.join(odoobaselib.SRC_DIR, repo))
    for addon in addons:
        src = os.path.join(odoobaselib.SRC_DIR, repo, addon)
        dst = os.path.join(odoobaselib.ADDONS_DIR, addon)
        logging.debug("Linking %s in %s", src, dst)
        os.symlink(src, dst)
