#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os
import shutil
import sys

import yaml

CLEAN = os.environ.get("CLEAN") == "yes"
SRC_DIR = "/opt/odoo/custom/src"

if not CLEAN:
    logging.warning("Not cleaning garbage")
    sys.exit()

with open(SRC_DIR + "/addons.yaml") as addons_file:
    config = yaml.load(addons_file)

# Config file could be empty
if config is None:
    config = dict()

# Special directories must be preserved
config.setdefault("private", "all")
config.setdefault("odoo", "all")

for directory in os.listdir(SRC_DIR):
    # Remove directories not listed in addons.yaml
    full = os.path.join(SRC_DIR, directory)
    if directory not in config:
        shutil.rmtree(full)
        continue

    # Skip addon repositories that need no cleaning
    if config[directory] == "all":
        continue

    # Traverse addons
    for subdirectory in os.listdir(full):
        subfull = os.path.join(full, subdirectory)
        # Skip regular files
        if not os.path.isdir(subfull):
            continue
        # Remove addon if not used
        if subdirectory not in config[directory]:
            shutil.rmtree(subfull)
