#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os
import shutil
import sys

import odoobaselib

if not odoobaselib.CLEAN:
    logging.warning("Not cleaning garbage")
    sys.exit()

config = odoobaselib.addons_config()
for directory in os.listdir(odoobaselib.SRC_DIR):
    # Special directories must be preserved
    if directory in {"private", "odoo"}:
        continue

    # Skip regular files
    full = os.path.join(odoobaselib.SRC_DIR, directory)
    if not os.path.isdir(full):
        continue

    # Remove directories not listed in addons.yaml
    if directory not in config:
        logging.info("Removing directory %s", full)
        shutil.rmtree(full)
        continue

    # Skip wildcards
    if '*' in config[directory]:
        continue

    # Traverse addons
    for subdirectory in os.listdir(full):
        subfull = os.path.join(full, subdirectory)
        # Skip regular files
        if not os.path.isdir(subfull):
            continue
        # Remove addon if not used
        if subdirectory not in config[directory]:
            logging.info("Removing subdirectory %s", subfull)
            shutil.rmtree(subfull)
