#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os
import shutil
import sys

from odoobaselib import addons_config, CORE, CLEAN, SRC_DIR

if not CLEAN:
    logging.warning("Not cleaning garbage")
    sys.exit()

addons = set(addons_config())
repos = {addon[1] for addon in addons}
for directory in os.listdir(SRC_DIR):
    # Special directories must be preserved
    if directory == "odoo":
        directory = CORE

    # Skip regular files
    full = os.path.join(SRC_DIR, directory)
    if not os.path.isdir(full):
        continue

    # Remove directories not listed in addons.yaml
    if directory not in repos:
        logging.info("Removing directory %s", full)
        shutil.rmtree(full)
        continue

    # Traverse addons
    for subdirectory in os.listdir(full):
        subfull = os.path.join(full, subdirectory)
        # Skip regular files
        if not os.path.isdir(subfull):
            continue
        # Remove addon if not used
        if (subdirectory, directory) not in addons:
            logging.info("Removing subdirectory %s", subfull)
            shutil.rmtree(subfull)
