#!/bin/bash
set -e

if [ "$COMPILE" != true ]; then
    log WARNING Not compiling Python code
    exit 0
fi

log INFO Compiling all Python code in /opt/odoo
# TODO Remove `|| true` when fixed https://github.com/odoo/odoo/issues/19871
PYTHONOPTIMIZE=2 python -m compileall -q /opt/odoo || true
