#!/bin/bash
set -e

if [ "$COMPILE" != true ]; then
    log WARNING Not compiling Python code
    exit 0
fi

log INFO Compiling all Python code in /opt/odoo
# TODO Remove `|| true` when odoo code compilation doesn't fail (v12?)
PYTHONOPTIMIZE=2 python -m compileall -q /opt/odoo || true
