#!/usr/bin/env bash
if [[ "$GEOIP_ACCOUNT_ID" != "" && "$GEOIP_LICENSE_KEY" != "" ]] ; then
    set -e
    # see https://dev.maxmind.com/geoip/geoipupdate/
    echo "Activating GeoIP/GeoLite2 updates"
    echo "This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com"
    echo "
# GeoIP.conf file for \`geoipupdate\` program, for versions >= 3.1.1.
# Used to update GeoIP databases from https://www.maxmind.com.
# For more information about this config file, visit the docs at
# https://dev.maxmind.com/geoip/geoipupdate/.

# \`AccountID\` is from your MaxMind account.
AccountID ${GEOIP_ACCOUNT_ID}

# Replace YOUR_LICENSE_KEY_HERE with an active license key associated
# with your MaxMind account.
LicenseKey ${GEOIP_LICENSE_KEY}

# \`EditionIDs\` is from your MaxMind account.
EditionIDs GeoLite2-City
    " > /etc/GeoIP.conf
    curl --silent -output geoipupdate_${GEOIP_UPDATER_VERSION}_linux_amd64.deb https://github.com/maxmind/geoipupdate/releases/download/v${GEOIP_UPDATER_VERSION}/geoipupdate_${GEOIP_UPDATER_VERSION}_linux_amd64.deb
    dpkg -i --force-confold geoipupdate_${GEOIP_UPDATER_VERSION}_linux_amd64.deb
    rm geoipupdate_${GEOIP_UPDATER_VERSION}_linux_amd64.deb
    chown -R root:odoo /usr/share/GeoIP/
    chmod g+w /usr/share/GeoIP/

    if [[ ! -e /opt/odoo/common/conf.d/60-geoip.conf ]] ; then
        echo "
[options]
# This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com
geoip_database=/usr/share/GeoIP/GeoLite2-City.mmdb
        " > /opt/odoo/common/conf.d/60-geoip.conf
    fi
fi
