#!/usr/bin/env bash
set -e
chown -R root:odoo /usr/share/GeoIP/ /etc/GeoIP.conf
chmod g+w /usr/share/GeoIP/ /etc/GeoIP.conf
if [[ "$GEOIP_ACCOUNT_ID" != "" && "$GEOIP_LICENSE_KEY" != "" ]] ; then
    # see https://dev.maxmind.com/geoip/geoipupdate/
    log INFO "Activating GeoIP/GeoLite2 updates"
    log INFO "This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com"
    sed 's/^AccountID\s.*$/AccountID '"$GEOIP_ACCOUNT_ID"'/g;s/^LicenseKey\s.*$/LicenseKey '"$GEOIP_LICENSE_KEY"'/g' /etc/GeoIP.conf > /tmp/GeoIP.conf
    cat /tmp/GeoIP.conf > /etc/GeoIP.conf
    rm /tmp/GeoIP.conf
fi
