#!/usr/bin/env python
# Copyright 2017 LasLabs Inc.

import os

import odoobaselib
from installer import Installer


FILE_APT_BUILD = os.path.join(
    odoobaselib.CUSTOM_DIR, 'dependencies', 'apt_build.txt',
)
CLEANUP = ['apt', 'gem', 'npm']


if os.path.isfile(FILE_APT_BUILD):
    installer = Installer('apt', FILE_APT_BUILD)
    installer.remove()
    installer.cleanup()


for name in CLEANUP:
    req_file = os.path.join(
        odoobaselib.CUSTOM_DIR, 'dependencies', '%s.txt' % name,
    )
    if os.path.isfile(req_file):
        Installer(name, req_file).cleanup()
