#!/usr/bin/env python
from __future__ import print_function

import os
import stat

from argparse import ArgumentParser
from subprocess import check_call
from tempfile import NamedTemporaryFile

from doodbalib import logger

# Define CLI options
parser = ArgumentParser(
    description="Execute some code in this container's QA environment.")
parser.add_argument(
    "script", type=bytes,
    help="The source code that will be executed. "
         "It should start with a shebang.")
parser.add_argument(
    "arguments", nargs="*",
    help="Additional arguments passed to the script.")
args = parser.parse_args()

# Copy the source code to an executable file
executable = NamedTemporaryFile(delete=False)
with executable as fp:
    logger.debug("Insider script source code:\n%s", args.script)
    fp.write(args.script)
os.chmod(executable.name, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)

# Execute the script
cmd = [executable.name] + args.arguments
try:
    logger.debug("Executing %r", cmd)
    check_call(cmd)
finally:
    logger.debug("Deleting %s", executable.name)
    os.unlink(executable.name)
